### PR TITLE
Prevent key press arrow up / down from triggering #startSpinUp / #startSpinDown multiple times

### PR DESCRIPTION
**Pull request by LukasWillin**
Dear nkovacic

Currently when Im holding down one of the arrow keys (up/down) then the #startSpinUp / #startSpinDown methods are being called in series until I leave the key.
This results in a too fast spin down or up ignoring any settings.

I added an additional isKeyDown boolean that is set to true the first time the event is triggered by the correct key event (up/down).
The isKeyDown property is set to false again when the keyUpEvent is triggered. This works similar to the already existing isButtonTouching.

Also I changed the stopSpin function to be always forceing a stop. I made this change because I could not see the benefit of having the original mechanic in place. A canceled timeout will not create an interval that needs to be dealt with.

Greetings
Lukas Willin

### CODE REVIEW

**Comment by nkovacic** [comment]
I just reviewed your pull request and i agree that arrow keys should have the same mechanics as mouse click or touchdown.
But I dont agree why you removed the force flag in stopSpin. This is a feature where the stopSpin is called with a timeout specified in the options (stepIntervalDelay). A posibility would be if the stepIntervalDelay is 0 then the timeout mechanic is removed.

**Comment by LukasWillin** [comment]
Then I will revert the changes made to #stopSpin. And update the pull request.

**Comment by LukasWillin** [comment]
Hello Niko Kovačič

Im sorry I didnt react for a long time. I have merged my changes into your last commits.
Sadly I wasnt able to successfully run gulp dist this time. So you might need to do so if you will accept my changes in file "src/components/touchspin/touchspin.controller.ts".

I wish you a nice weekend.

Kind regards
Lukas

**Comment by nkovacic** [comment]
I have made a fix where I took inspiration from your pull request. I did not merge the pull request because there were so many issues with spacing.

**Comment by LukasWillin** [comment]
Fair enough. Apologies if I couldn't get it right. I'm fairly new to Web Developement.
Regards
Lukas

**Pull request closed without merging**
