### PR TITLE
Add keyUP & keyDown + inverted button Up/Down to match UX

### PR DESCRIPTION
**Pull request by matinfo**

### CODE REVIEW

**Comment by nkovacic** [comment]
I will review this PR in the following days

**Comment by nkovacic** [comment]
Removed the inverted up/down. Is there any reason you changed it?
The UX was consistent beacause usually the - is on the left side and the + on the right side.

**Comment by matinfo** [comment]
Is was more with vertical layout mode that the up/down was not natural. Sorry I focused on this vertical mode I use. Need to have in vertical mode the button up that increment and the button down that decrement.

**Comment by nkovacic** [comment]
Please provide a codepen or jsfiddle example so I can see where the UX problem is.

**Comment by matinfo** [comment]
<p data-height="265" data-theme-id="0" data-slug-hash="yaJRLy" data-default-tab="html,result" data-user="matinfo" data-embed-version="2" data-preview="true" class="codepen">See the Pen <a href="http://codepen.io/matinfo/pen/yaJRLy/">yaJRLy</a> by Mathieu Meylan (<a href="http://codepen.io/matinfo">@matinfo</a>) on <a href="http://codepen.io">CodePen</a>.</p>

<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

For vertical button only (verticalButtons = true):
1. class UP/Down are inverted: bootstrap-touchspin-down = vm.touchSpinOptions.buttonUpClass / bootstrap-touchspin-up = vm.touchSpinOptions.buttonDownClass (small bug).
2. if you click on button _+_ the number is decremented in place of incremented. If click the _up arrow_ number is decremented in place of incremented. But work ok/logical with mouse and keyboard  (need to work like for the jQuery clone: http://www.virtuosoft.eu/code/bootstrap-touchspin/)

**Comment by nkovacic** [comment]
Ok i see where the bug is.
Will post a fix for this.

**Comment by nkovacic** [comment]
Fixed https://github.com/nkovacic/angular-touchspin/releases/tag/1.3.1

**Pull request merged**
